RUNNING_MODE_PRE_TEST="PreTest"
RUNNING_MODE_TEST="Test"
RUNNING_MODE_DEV="Dev"
RUNNING_MODE_PROD="Prod"
RUNNING_MODE_CHOICES = [
    RUNNING_MODE_PRE_TEST,
    RUNNING_MODE_TEST,
    RUNNING_MODE_DEV,
    RUNNING_MODE_PROD
]

RUNNING_STEP_IMPORT="import"
RUNNING_STEP_TRANSFORM="transform"
RUNNING_STEP_ALL="all"
RUNNING_STEP_CHOICES = [
    RUNNING_STEP_IMPORT,
    RUNNING_STEP_TRANSFORM,
    RUNNING_STEP_ALL
]
