from .mapping import add_auth_resource_path_mapping
from .post_process import add_auth_resource_path, add_auth_resource_path_to_dataframe

post_process_plugins = [add_auth_resource_path]

post_process_plugins_on_dataframe = [add_auth_resource_path_to_dataframe]
